- name: Ensure package index updated (Debian)
  ansible.builtin.apt:
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: Ensure package index updated (RedHat)
  ansible.builtin.yum:
    update_cache: yes
  when: ansible_os_family == "RedHat"

- name: Set MOTD banner
  ansible.builtin.copy:
    dest: /etc/motd
    content: "Ansible Managed by {{ motd_user }}\n"
    owner: root
    group: root
    mode: '0644'

