ansible_become: true
ansible_become_method: sudo

motd_user: valdez

nginx_listen_port: 80

prometheus_listen_port: 9090
grafana_listen_port: 3000
node_exporter_version: "1.8.1"
prometheus_version: "2.53.0"
grafana_version: "10.4.0"

prometheus_scrape_interval: "15s"
prometheus_targets:
  - job_name: "node"
    metrics_path: "/metrics"
    static_configs:
      - targets:
          - "192.168.56.102:9100"
          - "192.168.56.103:9100"
          - "192.168.56.104:9100"

